### PR TITLE
Adding Support for CLion

### PR DESCRIPTION
**Pull request by pdet**

### CODE REVIEW

**Comment by hannes** [comment]
Thanks can you please also provide an example how to use this alternative build?

**Comment by pdet** [comment]
I don't think an example is necessary, you just need to open the project using Clion and you can automatically run/debug it in the IDE.

**Comment by hannes** [comment]
But isn't CMakeLists.txt actually a CMake build file?

**Comment by hannes** [comment]
Added a slightly modified version, thanks

**Pull request closed without merging**
